### ISSUE TITLE
can't specify users in users.conf

### ISSUE THREAD

**Issue by n1trux** [janvidar/uhub#74]
I took the standard Dockerfile and made a docker-compose.yml with the following content:

```
version: "3"

services:
  uhub:
    image: uhub
    build: ./build/uhub
    volumes:
      - ./conf:/conf
    ports:
      - "411:411"
      - "1511:1511"
```

Then I made a uhub.conf:

```
server_port=411
server_bind_addr=any
server_alt_ports = 1511

# The maximum amount of users allowed on the hub.
max_users=100

# If 1, will show a "Powered by uHub/{VERSION}".
show_banner=1

# If enabled then operating system and cpu architecture is part of the banner.
show_banner_sys_info=1

# Allow only registered users on the hub if set to 1.
registered_users_only=1

# A server name and description.
hub_name=Test Hub
hub_description=Powered by uHub

# Set this to 0, and the hub will disconnect everyone
hub_enabled=1

# Access control list (user database)
file_acl=/conf/users.conf
```

And an ACL:

```
user_admin      testadm:11admin11
```

When I want to connect with EiskaltDC++, I get the following messages:

```
[20:07:54] <Test Hub> Powered by uhub/0.5.1-git-78a7039 on Linux/AMD64
[20:07:54] <Test Hub> Hub is for registered users only
[20:07:54] *  Hub is for registered users only 
```

What am I doing wrong?
